import type { JornadaActivaDto } from '@/types/jornada';

export function createSemaforoFormState(jornada: JornadaActivaDto | null): Record<string, unknown> {
  return {
    idJornada: jornada?._id ?? '',
    idViaTramo: '',
    idControSem: '',
    municipio: jornada?.municipio ?? '',
    supervisor: jornada?.supervisor ?? '',
    numExterno: null as number | null,
    controlRef: '',
    ipRadio: '',
    ubicacion: { type: 'Point', coordinates: [] as number[] },
    lat: null as number | null,
    lng: null as number | null,
    sitio: '',
    semaforoFunciona: true,
    claseSem: '',
    numCaras: 1,
    obstruccion: '',
    visibilidadOptima: '',
    fase: '',
    accion: '',
    estadoGenPint: '',
    implementacion: '',
    pulsador: false,
    estadoPulsador: '',
    temporizador: false,
    estadoTemp: '',
    dispositivoAuditivo: false,
    estadoDispAud: '',
    tipoSoporte: '',
    estadoSoporte: '',
    pinturaSoporte: '',
    sistemaSoporte: '',
    estadoAnclaje: '',
    urlFotoSoporte: '',
    urlFotoAnclaje: '',
    urlFotoPulsador: '',
    urlFotoDispAud: '',
    caras: [],
    obs1: '',
    obs2: '',
    obs3: '',
    obs4: '',
    obs5: '',
    obs6: '',
    notasGenerales: '',
    urlFotoSemaforo: '',
  };
}

